// autogenerated solution file, for help see https://github.com/beakerandjake/advent-of-code-runner

/**
 * Returns the solution for part one of this puzzle.
 * @param {String} input - The input for this days puzzle.
 * @returns {Number|String}
 */
export const partOne = (input = '') => {
  throw new Error('partOne not implemented');
};

/**
 * Returns the solution for part two of this puzzle.
 * @param {String} input - The input for this days puzzle.
 * @returns {Number|String}
 */
export const partTwo = (input = '') => {
  throw new Error('partTwo not implemented');
};
