# Workflow to validate pull requests on main branch. Runs tests and linting and updates code coverage.

name: CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Packages
      run: npm ci
          
      # Collect coverage data only on LTS version of node
    - name: Run Tests (With Coverage)
      run: npm test -- --coverage 
      if: matrix.node-version == '18.x'   
      
      # Test without collection coverage data on non-LTS version of node
    - name: Run Tests (Without Coverage)
      run: npm test
      if: matrix.node-version != '18.x'  
      
#     - name: Upload Coverage to Codecov
#       uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70
#       if: matrix.node-version == '18.x'   
      
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Install Packages
      run: npm ci
      
    - name: Linting
      run: npm run lint
