# Workflow to validate pull requests on main branch. Runs tests and linting and updates code coverage.

name: CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Packages
      run: npm ci
      
    - name: Linting
      run: npm run lint
    
      # Collect coverage data only on LTS version of node
    - name: Run Tests (With Coverage)
      run: npm test -- --coverage 
      if: matrix.node-version == '18.x'   
      
      # Test without collection coverage data on non-LTS version of node
    - name: Run Tests (Without Coverage)
      run: npm test
      if: matrix.node-version != '18.x'  

      # Updload coverage data to coveralls.io only on LTS version of node.
    - name: Upload Coverage to Coveralls
      uses: coverallsapp/github-action@1.1.3
      if: matrix.node-version == '18.x'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
