# Workflow to validate pull requests on main branch. Runs tests and linting and updates code coverage.

name: CI
run-name: CI for PR - ${{ github.event.pull_request.title || 'N/A' }}

on:
#   pull_request:
#     branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  coverage:
    name: Test with Coverage (Node LTS)
    runs-on: ubuntu-latest
    steps:      
    - name: Harden runner
      uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
      with:
        disable-telemetry: true
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          codecov.io:443
          github.com:443
          registry.npmjs.org:443
          storage.googleapis.com:443
          uploader.codecov.io:443
      
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Install Packages
      run: npm ci
      
    - name: Run Tests (With Coverage)
      run: npm test -- --coverage 
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 #v3.1.1 
      with:
        fail_ci_if_error: true
      
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Install Packages
      run: npm ci
      
    - name: Linting
      run: npm run lint
    
  # Run tests without coverage on non-lts versions of node.
  tests:
    name: Test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Packages
        run: npm ci

      - name: Run Tests
        run: npm test
