name: Create Github Release
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          egress-policy: audit
          
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_FOR_GITHUB }}
            
      - name: Release Test
        uses: anton-yurchenko/git-release@7900df3074616ce2667340e6a9c03c4d2971405b
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
