name: Create Github Release
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          disable-sudo: true
          egress-policy: block
          disable-telemetry: true
          allowed-endpoints: >
            github.com:443
            registry.npmjs.org:443
            
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_FOR_GITHUB }}
          
      - id: get-changelog
        name: Get changelog
        uses: superfaceai/release-changelog-action@b1411d74107d4691016c93940673c67535a927aa
        with:
          path-to-changelog: CHANGELOG.md
          version: 1.3.1-beta.4
          operation: read
          
      - name: Log changelog
        run: echo "${{ steps.get-changelog.outputs.changelog }}"
