# Creates a new npm release of this package

name: Publish to npm
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_GITHUB_PAT }}
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
        
#       - name: Run Tests
#         run: |
#           npm ci
#           npm test  

      - name: Get Version
        run: echo "NEW_VERSION=$(npm pkg get version | sed 's/"//g')" >> $GITHUB_ENV
        
      - name: Set npm dist tag (@prerelease)
        if: contains(env.NEW_VERSION, 'beta') || contains(env.NEW_VERSION, 'alpha')
        run: echo "NPM_DIST_TAG=beta" >> $GITHUB_ENV
          
      - name: Run npm publish (@prerelease)
        if: env.NPM_DIST_TAG != null
        run: echo 'PRERELEASE!'
        
      - name: Run npm publish (@latest)
        if: env.NPM_DIST_TAG == null
        run: echo 'LATEST'
        
      - name: Git tag
        run: |
          git tag ${{ format('v{0}', env.NEW_VERSION) }}
          git push origin ${{ format('v{0}', env.NEW_VERSION) }}
