name: Publish to NPM
on:
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Configure Git User
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
     
#       - name: Install dependencies
#         run: npm ci
  
#       - name: Run Tests
#         run: npm test
      
      - name: Configure Git User
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
      - name: Get Version from package.json
        run: echo "NEW_VERSION=$(npm pkg get version | sed 's/"//g')" >> $GITHUB_ENV
        
      - name: Git Tag
        run: git tag ${{ format('v{0}', env.NEW_VERSION) }}
        
      - name: Push tag
        run: git push --tags

#       - name: Version (pre-release)
#         if: startsWith(github.event.inputs.release-type, 'pre')
#         run: |
#           echo "NEW_VERSION=$(npm --no-git-tag-version --preid=beta version $RELEASE_TYPE)" >> $GITHUB_ENV
#           echo "RELEASE_TAG=beta" >> $GITHUB_ENV
#         env:
#           RELEASE_TYPE: ${{ github.event.inputs.release-type }}
            
#       - name: Commit changes and tag
#         run: |
#           git add "package.json"
#           git add "package-lock.json"
#           git add "CHANGELOG.md"
#           git commit -m "chore: release ${{ env.NEW_VERSION }}"
#           git tag ${{ env.NEW_VERSION }}

#       - name: Publish to npm
#         run: npm publish --tag ${{ env.RELEASE_TAG }}
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          
#       - name: Push changes to repository
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           git push origin && git push --tags
