name: Test Changelog PR comment

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Check for CHANGELOG modified
        id: changelog
        uses: tj-actions/changed-files@db3ea27a0cf07135175be5efe7aaf84df6e0e6f0 # v35.5.0
        with:
          files: |
            CHANGELOG.md
            
      - name: Add Comment to PR if CHANGELOG not modified.
        if: steps.changelog.outputs.any_changed == false
        run:
          echo 'I NEED TO ADD A COMMENT!'
          
